### ISSUE TITLE
Generate APIs

### ISSUE THREAD

**Issue by elit0451** [DavidCarl/test2019-exam#33]
## Description
The APIs are needed to integrate the back-end logic of our system with the front-end. These will be composed of controllers mimicking the already existing functionality. APIs should be created for the behaviour of teachers, students and the principal.

## List of requirements
- [x] Teacher API [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XNQGvt-3qwAPIY2y) #35
- [x] Student API [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XNQGxFUnwwAPpAMv) #36
- [x] Principal API [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XNQG6t-3qwAPIY2_) #37

## Acceptance Criteria
1. APIs can be spun up on a server
1. APIs respond with the proper HTTP codes
1. The APIs response should provide properly formatted and in a standardized format (JSON)
1. The APIs should be properly tested
