### ISSUE TITLE
Frontend Specification

### ISSUE THREAD

**Issue by DavidCarl** [DavidCarl/test2019-exam#34]
## 📋 Frontend specification
This is for the Frontend. Here we are going to to specify what we need to implement in the frontend part.

## Description
The frontend is supposed to be where our user goto for a better experience. The plan is to make this webbased.

## List of requirements

- [ ] Teacher Signup [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XNQIICLT1gAbLrs0) #38 
- [ ] Teacher control panel [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XNQJCyLT1gAbLrtE) #39 
- [ ] Student signup [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XNQJWyLT1gAbLrtX) #40
- [ ] Student control panel [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XNQJyyLT1gAbLrtc) #41
- [ ] Principal control panel [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XNQKjCLT1gAbLrtx) #42
- [ ] Course overview [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XNQMUiLT1gAbLruw) #43
- [ ] Specific course overview [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XNQM4CLT1gAbLrvA) #44
- [ ] Overview panel [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XNQOAiLT1gAbLrvk) #45

## Acceptance Criteria
1. Being able to register as a new teacher
1. Being able to register as a new student
1. Being able to control yourself as a teacher
1. Being able to control yourself as a student
1. Being able to add new courses as a principal
1. Being able to assign a teacher to a course
1. Being able to see all courses
1. Being able to see specific details about a course
1. Being able to get a overview of teachers and students

## Non-functional requirements 
Nothing here yet
