### ISSUE TITLE
LES Specifications

### ISSUE THREAD

**Issue by DavidCarl** [DavidCarl/test2019-exam#4]
## 📋 LES Specifications
This is the main organization of our task, this controls a lot of underlying things going on.

## Description
LES is controlling the cleanup according to the rules and giving permissions to other roles to perform their actions. It also controls semester durations.

## List of requirements
- [ ] Removes unpaid teachers after 5 years (inactive) [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbFrR3amQAPaSX0) #9 
- [ ] Courses can only be offered for 3 years [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbGWR3amQAPaSX9) #10
- [ ] Stats saved 2 years after course [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbNYB3amQAPaSbz) #13
- [ ] Cleanup after semester. [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbZux3amQAPaSkT) #18 
- [ ] Semester duration (September 1st - December 31st, and January 1st - May 1st) [parent of](#) 

## Acceptance Criteria
1. Removes unpaid teachers after 5 years (inactive)
2. Courses can only be offered for 3 years 
3. Stats saved 2 years after course
4. Cleanup after semester. 
5. Semester duration (September 1st - December 31st, and January 1st - May 1st) 

## Non-functional requirements 
Nothing here yet

## Additional information
Some of these Acceptance Criteria is probably shared with some other Epics since this is a very underlying epic.
