### ISSUE TITLE
Topic Specifications

### ISSUE THREAD

**Issue by elit0451** [DavidCarl/test2019-exam#5]
## Description
A topic will hold multiiple courses, and manages them. Including the registry, deletion and obtaining information about a course.  

## List of requirements
- [x] Add a course [parent of ](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbKN2MNkgAP7AqT)#12
- [x] Get a course  [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbRvlUnwwAPosU2) #14
- [x] Delete a course [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbTs2MNkgAP7AvN) #15

## Acceptance Criteria
1.  A topic can be offered for a max 3y. 
1.  A topic should hold  a list of courses.
