### ISSUE TITLE
Course Specifications

### ISSUE THREAD

**Issue by elit0451** [DavidCarl/test2019-exam#6]
## Description
A course defines a component of a topic. It needs a teacher and a room. Students should be able to enrol in a course while the number of allowed students per course isn't exceeded. A course can only start if on its start data at least 9 students are enrolled. When adding a course we need to check if its teacher is eligible. 

## List of requirements
- [x] Enrol to course [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbWbGMNkgAP7Awp) #16
- [ ] Start course [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbWmN-3qwAPIFFj) #17
- [x] Receive Payment [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbayVUnwwAPosZ9) #19

## Acceptance Criteria
1. Validate teacher eligibility
1. Validate student age and payment
1. Keep a list of students
1. Course has st​art date
