### ISSUE TITLE
Teacher Specifications

### ISSUE THREAD

**Issue by DavidCarl** [DavidCarl/test2019-exam#7]
## 📋 Teacher specifications
This is the teacher specifications, here we have whatever has with the teacher todo.

## Description
The teacher teaches the courses. They have a max amount of teachings on a semester. Their voting rights are also depending on previous semesters teaching amount, and a teacher need a specific level of education background.

## List of requirements

- [x] 3 max concurrent courses at a time [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbbnh3amQAPaSlB) #20 
- [x] Amount of hours worked the previous semester [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbbnh3amQAPaSlB) #20 
- [x] Education background [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbbnh3amQAPaSlB) #20 

## Acceptance Criteria
(Write your criteria here:)
1. 3 max concurrent courses at a time
2. Amount of hours worked the previous semester 
3. Education background

## Non-functional requirements 
Nothing here yet
