### ISSUE TITLE
Principal Specifications

### ISSUE THREAD

**Issue by DavidCarl** [DavidCarl/test2019-exam#8]
## 📋 Principal specification
This is the principle, which basically is the same as admin.

## Description
Principle controls the registration of teachers and courses, and the hiring of teachers.

## List of requirements

- [ ] Create courses [parent of]() #12 
- [ ] Hire teachers to a course [parent of]() #20 
- [ ] Hire new teachers and perform background check [parent of] #20 
- [ ] Do nothing once semester starts
- [ ] Create topics to put courses under [parent of](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XMbgPR3amQAPaSmy) #21

## Acceptance Criteria
(Write your criteria here:)
1. Create courses
2. Hire teachers to a course
3. Hire new teachers and perform background check
4. Do nothing once semester starts
5. Create topics to put courses under 

## Non-functional requirements 
Nothing here yet
