### ISSUE TITLE
Goal before delivery

### ISSUE THREAD

**Issue by DavidCarl** [DavidCarl/test2019-exam#83]
We want the following implemented before Friday!

- [ ] Parameterized test parent of [#84](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XOKGU_JVrgAPK9AH)
- [ ] Database parent of [#85](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XOKHMqkSegAPdv4e)
- [ ] Gerkin / Cucumber parent of [#86](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XOKHpul69gASDW9M)
- [ ] Continuous Delivery parent of [#87](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XOKIKOl69gASDW9Z)
- [ ] Report parent of [#88](https://app.gitkraken.com/glo/board/XMajht-3qwAPIEpI/card/XOKIXSy2igAPVK2a)
